package org.gbxteam.betterview.sys.settings;

import org.gbxteam.betterview.BFPMain;
import org.gbxteam.betterview.core.engine.controller.JointAnimator;
import org.gbxteam.betterview.core.engine.controller.JointAnimatorRegistry;
import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.*;
import dev.isxander.yacl3.impl.controller.TickBoxControllerBuilderImpl;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.entity.BlockEntityType;

import java.text.DecimalFormat;
import java.util.Objects;

import net.minecraft.client.Minecraft;

public class BFPConfigScreen {

    /**
     * Primary entry point for ModMenu: The Quick Settings Screen.
     * Contains only the 3 most crucial options and a link to the Advanced Settings.
     */
    public static Screen createConfigScreen(Screen parentScreen) {
        BFPConfig config = BFPMain.CONFIG;
        config.load();

        return YetAnotherConfigLib.createBuilder()
                .title(Component.translatable("bfp.config.title.quick"))
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("bfp.config.category.quick.name"))
                        .tooltip(Component.translatable("bfp.config.category.quick.tooltip"))
                        
                        // 1. Enable First Person Renderer
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("bfp.config.option.enable_first_person_renderer.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.enable_first_person_renderer.description"))
                                        .build())
                                .binding(true, () -> config.data().firstPersonPlayer.enableRenderer, newValue -> config.data().firstPersonPlayer.enableRenderer = newValue)
                                .controller(option -> BooleanControllerBuilder.create(option)
                                        .formatValue(state -> state ? Component.translatable("bfp.config.option.enable_first_person_renderer.enabled") : Component.translatable("bfp.config.option.enable_first_person_renderer.disabled"))
                                        .coloured(true))
                                .build())
                        // 2. Camera Shake Master Intensity
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("bfp.config.option.first_person_camera_shake_intensity_master.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.first_person_camera_shake_intensity_master.description"))
                                        .build())
                                .binding(1.0f, () -> config.data().firstPersonPlayer.cameraShakeMasterIntensity, newValue -> config.data().firstPersonPlayer.cameraShakeMasterIntensity = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new java.text.DecimalFormat("0.00").format(value)))
                                        .range(0.00f, 1.00f)
                                        .step(0.01f))
                                .build())
                        // 3. Mining Animation Speed
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("bfp.config.option.first_person_mining_speed.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.first_person_mining_speed.description"))
                                        .build())
                                .binding(1f, () -> config.data().firstPersonPlayer.miningAnimationSpeedMultiplier, newValue -> config.data().firstPersonPlayer.miningAnimationSpeedMultiplier = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new java.text.DecimalFormat("0.00").format(value)))
                                        .range(0.25f, 2.00f)
                                        .step(0.01f))
                                .build())
                        // Button to Advanced Settings
                        .option(ButtonOption.createBuilder()
                                .name(Component.translatable("bfp.config.button.advanced.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.button.advanced.description"))
                                        .build())
                                .action((yaclScreen, buttonOption) -> Minecraft.getInstance().setScreen(createAdvancedConfigScreen(yaclScreen)))
                                .build())
                        .build())
                .save(config::save)
                .build()
                .generateScreen(parentScreen);
    }

    /**
     * The deeply categorized Advanced Settings Screen.
     */
    public static Screen createAdvancedConfigScreen(Screen parentScreen) {

        BFPConfig config = BFPMain.CONFIG;
        config.load();

        return YetAnotherConfigLib.createBuilder()
                .title(Component.translatable("bfp.config.title.advanced"))
                .category(firstPersonPlayerConfig(config))
                .category(combatWeaponsConfig(config))
                .category(blockEntitiesConfig(config))
                .save(config::save)
                .build()
                .generateScreen(parentScreen);
    }

    private static ConfigCategory firstPersonPlayerConfig(BFPConfig config) {
        return ConfigCategory.createBuilder()
                .name(Component.translatable("bfp.config.category.first_person_player.name"))
                .tooltip(Component.translatable("bfp.config.category.first_person_player.tooltip"))
                
                // Group: General & Positioning
                .group(OptionGroup.createBuilder()
                        .name(Component.translatable("bfp.config.group.general_positioning.name"))
                        .description(OptionDescription.createBuilder()
                                .text(Component.translatable("bfp.config.group.general_positioning.description"))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("bfp.config.option.enable_first_person_renderer.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.enable_first_person_renderer.description"))
                                        .build())
                                .binding(true, () -> config.data().firstPersonPlayer.enableRenderer, newValue -> config.data().firstPersonPlayer.enableRenderer = newValue)
                                .controller(option -> BooleanControllerBuilder.create(option)
                                        .formatValue(state -> state ? Component.translatable("bfp.config.option.enable_first_person_renderer.enabled") : Component.translatable("bfp.config.option.enable_first_person_renderer.disabled"))
                                        .coloured(true))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("bfp.config.option.first_person_arm_offset_x.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.first_person_arm_offset_x.description"))
                                        .build())
                                .binding(0.0f, () -> config.data().firstPersonPlayer.armOffsetX, newValue -> config.data().firstPersonPlayer.armOffsetX = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.0").format(value)))
                                        .range(-16.00f, 16.00f)
                                        .step(0.1f))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("bfp.config.option.first_person_arm_offset_y.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.first_person_arm_offset_y.description"))
                                        .build())
                                .binding(0.0f, () -> config.data().firstPersonPlayer.armOffsetY, newValue -> config.data().firstPersonPlayer.armOffsetY = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.0").format(value)))
                                        .range(-16.00f, 16.00f)
                                        .step(0.1f))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("bfp.config.option.first_person_arm_offset_z.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.first_person_arm_offset_z.description"))
                                        .build())
                                .binding(0.0f, () -> config.data().firstPersonPlayer.armOffsetZ, newValue -> config.data().firstPersonPlayer.armOffsetZ = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.0").format(value)))
                                        .range(-16.00f, 16.00f)
                                        .step(0.1f))
                                .build())
                        .build())

                // Group: Animation Dynamics
                .group(OptionGroup.createBuilder()
                        .name(Component.translatable("bfp.config.group.animation_dynamics.name"))
                        .description(OptionDescription.createBuilder()
                                .text(Component.translatable("bfp.config.group.animation_dynamics.description"))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("bfp.config.option.first_person_mining_speed.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.first_person_mining_speed.description"))
                                        .build())
                                .binding(1f, () -> config.data().firstPersonPlayer.miningAnimationSpeedMultiplier, newValue -> config.data().firstPersonPlayer.miningAnimationSpeedMultiplier = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.25f, 2.00f)
                                        .step(0.01f))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("bfp.config.option.running_arm_swing_intensity.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.running_arm_swing_intensity.description"))
                                        .build())
                                .binding(1f, () -> config.data().firstPersonPlayer.runningArmSwingIntensity, newValue -> config.data().firstPersonPlayer.runningArmSwingIntensity = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.00f, 1.00f)
                                        .step(0.01f))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("bfp.config.option.first_person_map_movement_animation_intensity.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.first_person_map_movement_animation_intensity.description"))
                                        .build())
                                .binding(0.2f, () -> config.data().firstPersonPlayer.mapMovementAnimationIntensity, newValue -> config.data().firstPersonPlayer.mapMovementAnimationIntensity = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.00f, 1.00f)
                                        .step(0.01f))
                                .build())
                        .build())

                // Group: Camera Shake Effects
                .group(OptionGroup.createBuilder()
                        .name(Component.translatable("bfp.config.group.first_person_camera_shake.name"))
                        .description(OptionDescription.createBuilder()
                                .text(Component.translatable("bfp.config.group.first_person_camera_shake.description"))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("bfp.config.option.first_person_camera_shake_intensity_master.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.first_person_camera_shake_intensity_master.description"))
                                        .build())
                                .binding(1.0f, () -> config.data().firstPersonPlayer.cameraShakeMasterIntensity, newValue -> config.data().firstPersonPlayer.cameraShakeMasterIntensity = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.00f, 1.00f)
                                        .step(0.01f))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("bfp.config.option.first_person_camera_shake_intensity_movement.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.first_person_camera_shake_intensity_movement.description"))
                                        .build())
                                .binding(1.0f, () -> config.data().firstPersonPlayer.cameraShakeMovementIntensity, newValue -> config.data().firstPersonPlayer.cameraShakeMovementIntensity = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.00f, 1.00f)
                                        .step(0.01f))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("bfp.config.option.first_person_camera_shake_intensity_item_interactions.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.first_person_camera_shake_intensity_item_interactions.description"))
                                        .build())
                                .binding(0.5f, () -> config.data().firstPersonPlayer.cameraShakeItemInteractionIntensity, newValue -> config.data().firstPersonPlayer.cameraShakeItemInteractionIntensity = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.00f, 1.00f)
                                        .step(0.01f))
                                .build())
                        .build())
                // Group: Camera Overhaul Physics
                .group(OptionGroup.createBuilder()
                        .name(Component.translatable("bfp.config.group.camera_overhaul.name"))
                        .description(OptionDescription.createBuilder()
                                .text(Component.translatable("bfp.config.group.camera_overhaul.description"))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("bfp.config.option.enable_camera_overhaul.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.enable_camera_overhaul.description"))
                                        .build())
                                .binding(true, () -> config.data().firstPersonPlayer.enableCameraOverhaul, newValue -> config.data().firstPersonPlayer.enableCameraOverhaul = newValue)
                                .controller(option -> BooleanControllerBuilder.create(option).coloured(true))
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("bfp.config.option.co_strafing_roll.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.co_strafing_roll.description"))
                                        .build())
                                .binding(10.0, () -> config.data().firstPersonPlayer.coStrafingRollFactor, newValue -> config.data().firstPersonPlayer.coStrafingRollFactor = newValue)
                                .controller(option -> DoubleSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.0").format(value)))
                                        .range(0.0, 25.0)
                                        .step(0.5))
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("bfp.config.option.co_forward_pitch.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.co_forward_pitch.description"))
                                        .build())
                                .binding(7.0, () -> config.data().firstPersonPlayer.coForwardVelocityPitchFactor, newValue -> config.data().firstPersonPlayer.coForwardVelocityPitchFactor = newValue)
                                .controller(option -> DoubleSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.0").format(value)))
                                        .range(0.0, 20.0)
                                        .step(0.5))
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("bfp.config.option.co_vertical_pitch.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.co_vertical_pitch.description"))
                                        .build())
                                .binding(2.5, () -> config.data().firstPersonPlayer.coVerticalVelocityPitchFactor, newValue -> config.data().firstPersonPlayer.coVerticalVelocityPitchFactor = newValue)
                                .controller(option -> DoubleSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.0").format(value)))
                                        .range(0.0, 10.0)
                                        .step(0.5))
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("bfp.config.option.co_turning_roll_intensity.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.co_turning_roll_intensity.description"))
                                        .build())
                                .binding(1.25, () -> config.data().firstPersonPlayer.coTurningRollIntensity, newValue -> config.data().firstPersonPlayer.coTurningRollIntensity = newValue)
                                .controller(option -> DoubleSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.0, 5.0)
                                        .step(0.25))
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("bfp.config.option.co_turning_roll_smoothing.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.co_turning_roll_smoothing.description"))
                                        .build())
                                .binding(1.0, () -> config.data().firstPersonPlayer.coTurningRollSmoothing, newValue -> config.data().firstPersonPlayer.coTurningRollSmoothing = newValue)
                                .controller(option -> DoubleSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.1, 3.0)
                                        .step(0.1))
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("bfp.config.option.co_horizontal_smoothing.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.co_horizontal_smoothing.description"))
                                        .build())
                                .binding(1.0, () -> config.data().firstPersonPlayer.coHorizontalVelocitySmoothing, newValue -> config.data().firstPersonPlayer.coHorizontalVelocitySmoothing = newValue)
                                .controller(option -> DoubleSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.1, 3.0)
                                        .step(0.1))
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("bfp.config.option.co_vertical_smoothing.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.co_vertical_smoothing.description"))
                                        .build())
                                .binding(1.0, () -> config.data().firstPersonPlayer.coVerticalVelocitySmoothing, newValue -> config.data().firstPersonPlayer.coVerticalVelocitySmoothing = newValue)
                                .controller(option -> DoubleSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.1, 3.0)
                                        .step(0.1))
                                .build())
                        .build())

                // Group: Procedural Arm Physics
                .group(OptionGroup.createBuilder()
                        .name(Component.translatable("bfp.config.group.first_person_arm_camera_damping.name"))
                        .description(OptionDescription.createBuilder()
                                .text(Component.translatable("bfp.config.group.first_person_arm_camera_damping.description"))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("bfp.config.option.enable_first_person_arm_camera_damping.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.enable_first_person_arm_camera_damping.description"))
                                        .build())
                                .binding(true, () -> config.data().firstPersonPlayer.enableCameraRotationDamping, newValue -> config.data().firstPersonPlayer.enableCameraRotationDamping = newValue)
                                .controller(option -> BooleanControllerBuilder.create(option).coloured(true))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("bfp.config.option.first_person_arm_camera_stiffness_factor.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.first_person_arm_camera_stiffness_factor.description"))
                                        .build())
                                .binding(0.3f, () -> config.data().firstPersonPlayer.cameraRotationStiffnessFactor, newValue -> config.data().firstPersonPlayer.cameraRotationStiffnessFactor = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.01f, 1.00f)
                                        .step(0.01f))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("bfp.config.option.first_person_arm_camera_damping_factor.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.first_person_arm_camera_damping_factor.description"))
                                        .build())
                                .binding(0.7f, () -> config.data().firstPersonPlayer.cameraRotationDampingFactor, newValue -> config.data().firstPersonPlayer.cameraRotationDampingFactor = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.01f, 1.00f)
                                        .step(0.01f))
                                .build())
                        .build())
                .build();
    }

    private static ConfigCategory combatWeaponsConfig(BFPConfig config) {
        return ConfigCategory.createBuilder()
                .name(Component.translatable("bfp.config.category.combat_weapons.name"))
                .tooltip(Component.translatable("bfp.config.category.combat_weapons.tooltip"))

                // Group: Cinematic & Dynamic Combat
                .group(OptionGroup.createBuilder()
                        .name(Component.translatable("bfp.config.group.dynamic_combat.name"))
                        .description(OptionDescription.createBuilder()
                                .text(Component.translatable("bfp.config.group.dynamic_combat.description"))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("bfp.config.option.cinematic_combat_mode.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.cinematic_combat_mode.description"))
                                        .build())
                                .binding(false, () -> config.data().combatAndWeapons.cinematicCombatMode, newValue -> config.data().combatAndWeapons.cinematicCombatMode = newValue)
                                .controller(option -> BooleanControllerBuilder.create(option).coloured(true))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("bfp.config.option.dynamic_weapon_weight.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.dynamic_weapon_weight.description"))
                                        .build())
                                .binding(true, () -> config.data().combatAndWeapons.dynamicWeaponWeight, newValue -> config.data().combatAndWeapons.dynamicWeaponWeight = newValue)
                                .controller(option -> BooleanControllerBuilder.create(option).coloured(true))
                                .build())
                        .build())

                // Group: Combat Sway Modifiers
                .group(OptionGroup.createBuilder()
                        .name(Component.translatable("bfp.config.group.combat_sway_modifiers.name"))
                        .description(OptionDescription.createBuilder()
                                .text(Component.translatable("bfp.config.group.combat_sway_modifiers.description"))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("bfp.config.option.combat_sway_multiplier.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.combat_sway_multiplier.description"))
                                        .build())
                                .binding(1.0f, () -> config.data().combatAndWeapons.combatSwayMultiplier, newValue -> config.data().combatAndWeapons.combatSwayMultiplier = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.00f, 3.00f)
                                        .step(0.05f))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("bfp.config.option.heavy_weapon_penalty.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.heavy_weapon_penalty.description"))
                                        .build())
                                .binding(1.5f, () -> config.data().combatAndWeapons.heavyWeaponSwayPenalty, newValue -> config.data().combatAndWeapons.heavyWeaponSwayPenalty = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(1.00f, 3.00f)
                                        .step(0.05f))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("bfp.config.option.light_weapon_bonus.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.light_weapon_bonus.description"))
                                        .build())
                                .binding(0.8f, () -> config.data().combatAndWeapons.lightWeaponAgilityBonus, newValue -> config.data().combatAndWeapons.lightWeaponAgilityBonus = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.10f, 1.00f)
                                        .step(0.05f))
                                .build())
                        .build())
                .build();
    }

    private static ConfigCategory blockEntitiesConfig(BFPConfig config) {
        ConfigCategory.Builder categoryBuilder = ConfigCategory.createBuilder();
        categoryBuilder.name(Component.translatable("bfp.config.category.block_entities.name"));
        categoryBuilder.tooltip(Component.translatable("bfp.config.category.block_entities.tooltip"));

        categoryBuilder.group(OptionGroup.createBuilder()
                .name(Component.translatable("bfp.config.group.block_entity_optimization.name"))
                .description(OptionDescription.createBuilder()
                        .text(Component.translatable("bfp.config.group.block_entity_optimization.description"))
                        .build())
                .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("bfp.config.option.block_entity_animation_distance.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("bfp.config.option.block_entity_animation_distance.description"))
                                        .build())
                                .binding(32, () -> config.data().blockEntities.evaluationDistance, newValue -> config.data().blockEntities.evaluationDistance = newValue)
                                .controller(option -> IntegerSliderControllerBuilder.create(option)
                                        .range(4, 128)
                                        .step(4))
                                .build())
                .option(Option.<JointAnimator.PoseCalculationFrequency>createBuilder()
                        .name(Component.translatable("bfp.config.option.block_entity_pose_calculation_frequency.name"))
                        .description(OptionDescription.createBuilder()
                                .text(Component.translatable("bfp.config.option.block_entity_pose_calculation_frequency.description"))
                                .build())
                        .binding(JointAnimator.PoseCalculationFrequency.CALCULATE_EVERY_FRAME, () -> config.data().blockEntities.poseCalculationFrequency, newValue -> config.data().blockEntities.poseCalculationFrequency = newValue)
                        .controller(option -> EnumControllerBuilder.create(option)
                                .enumClass(JointAnimator.PoseCalculationFrequency.class)
                                .formatValue(v -> Component.translatable("bfp.config.option.block_entity_pose_calculation_frequency.enum." + v.name().toLowerCase())))
                        .build())
                .build());

        OptionGroup.Builder blockTogglesBuilder = OptionGroup.createBuilder()
                .name(Component.translatable("bfp.config.group.individual_block_entity_toggles.name"))
                .description(OptionDescription.createBuilder()
                        .text(Component.translatable("bfp.config.group.individual_block_entity_toggles.description"))
                        .build());

        for (BlockEntityType<?> blockEntityType : JointAnimatorRegistry.getRegisteredBlockEntities()) {
            Identifier blockEntityTypeIdentifier = BlockEntityType.getKey(blockEntityType);
            assert blockEntityTypeIdentifier != null;
            blockTogglesBuilder.option(Option.<Boolean>createBuilder()
                    .name(Component.translatable("block." + blockEntityTypeIdentifier.toLanguageKey()))
                            .binding(
                                    false,
                                    () -> config.data().blockEntities.enabledBlockEntities.getOrDefault(blockEntityTypeIdentifier.toString(), true),
                                    newValue -> config.data().blockEntities.enabledBlockEntities.put(blockEntityTypeIdentifier.toString(), newValue)
                            )
                            .controller(option -> BooleanControllerBuilder.create(option).coloured(true))
                    .build());
        }

        categoryBuilder.group(blockTogglesBuilder.build());
        return categoryBuilder.build();
    }
}
